version: "3.9"

services:
  rag-system:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: rag_system_dev
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      CLO_HOST: 31.97.148.98
      CLO_PORT: "9933"
      OLLAMA_HOST: http://host.docker.internal:11434
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["uvicorn", "rag_api:app", "--host", "0.0.0.0", "--port", "8000"]


