"""
CLO 3D Companion - Configuration Module

Connection settings for CLO bridge integration.
"""

import os

# Host configuration
CLO_HOST = os.getenv("CLO_HOST", "127.0.0.1")

# Port configuration (default: 51235)
CLO_PORT = int(os.getenv("CLO_PORT", "51235"))

# Timeout for bridge commands (seconds)
CLO_TIMEOUT = int(os.getenv("CLO_TIMEOUT", "10"))

# Script export directory
CLO_SCRIPT_DIR = os.getenv("CLO_SCRIPT_DIR", "exports/clo_scripts")

# Bridge listener configuration
BRIDGE_ENABLED = os.getenv("CLO_BRIDGE_ENABLED", "1") == "1"

# Retry configuration
MAX_RETRIES = int(os.getenv("CLO_MAX_RETRIES", "3"))
RETRY_DELAY = int(os.getenv("CLO_RETRY_DELAY", "1"))  # seconds

# Logging
LOG_COMMANDS = os.getenv("CLO_LOG_COMMANDS", "1") == "1"

# Script generation settings
SCRIPT_TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates")
SCRIPT_HEADER = """
# Auto-generated CLO 3D script
# Generated by RAGGITY ZYZTEM 2.0
# Timestamp: {timestamp}
# Mode: {mode}
"""

# Supported CLO versions (for validation)
SUPPORTED_CLO_VERSIONS = ["6.0", "6.1", "6.2", "7.0", "7.1"]

# Default encoding for script files
SCRIPT_ENCODING = "utf-8"

